#
---
# create install dirs
- debug: var=harbor_install_tmp
- debug: var=harbor_install_dir

- name: create install dir1
  file: 
    path: '{{ harbor_install_tmp }}'
    state: directory

- name: create install dir2
  file:
    path: '{{ harbor_install_dir }}'
    state: directory

# download or upload tarball

- name: upload local copy
  copy: 
    src: '{{ harbor_install_upload_localcopy_of_installer }}'
    dest: '{{ harbor_install_tmp }}/{{ harbor_install_tgz }}'

# unpack 
- name: unpack harbor_install_tgz
  unarchive: 
    remote_src: True
    src: '{{ harbor_install_tmp }}/{{ harbor_install_tgz }}'
    dest: '{{ harbor_install_dir }}'

# config template
- name: upload harbor.cfg from template
  template: 
    src: harbor.cfg.j2
    dest: '{{ harbor_install_dir }}/harbor/harbor.cfg'

# Data directory modification
- name: renaming the data directory inside docker-compose.yml
  replace:
    path: '{{ harbor_install_dir }}/harbor/docker-compose.yml'
    regexp: '(\s+\-\s)/data(/)'
    replace: '\1{{ harbor_secretkey_path }}\2'
    backup: yes

- name: changing http port inside docker-compose.yml
  replace:
    path: '{{ harbor_install_dir }}/harbor/docker-compose.yml'
    regexp: '(?P<uno>-\s+)80(?P<dos>:\d+$)'
    replace: '\g<uno>{{ harbor_http_port }}\g<dos>'

- name: changing https port inside docker-compose.yml
  replace:
    path: '{{ harbor_install_dir }}/harbor/docker-compose.yml'
    regexp: '(?P<uno>-\s+)443(?P<dos>:\d+$)'
    replace: '\g<uno>{{ harbor_https_port }}\g<dos>'

- name: renaming the data directory inside docker-compose.clair.yml
  replace:
    path: '{{ harbor_install_dir }}/harbor/docker-compose.clair.yml'
    regexp: '(\s+\-\s)/data(/)'
    replace: '\1{{ harbor_secretkey_path }}\2'
    backup: yes

- name: renaming the data directory inside docker-compose.notary.yml
  replace:
    path: '{{ harbor_install_dir }}/harbor/docker-compose.notary.yml'
    regexp: '(\s+\-\s)/data(/)'
    replace: '\1{{ harbor_secretkey_path }}\2'
    backup: yes

- name: inserting personalized https port for redirecting module nginx
  replace:
    path: '{{ harbor_install_dir }}/harbor/common/templates/nginx/nginx.https.conf'
    regexp: '(?P<uno>\$\$host)(?P<dos>\$\$request_uri)'
    replace: '\g<uno>:{{ harbor_https_port }}\g<dos>'
    backup: yes

# run installer
- name: run harbor install script
  shell: './install.sh --with-notary --with-clair > {{ harbor_install_dir }}/harbor_install_log.txt'
  args:
    chdir: '{{ harbor_install_dir }}/harbor'
    # don't reinstall / figure out what when wrong and delete or move the logfile
    creates: '{{ harbor_install_dir }}/harbor_install_log.txt'

